website/urls.py
from django.conf.urls import patterns, include, url
from website.views import hello, current_datetime, hours_ahead, display_meta
from books.views import search, search_form#views
from contact.views import contact, thanks
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'website.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^hello/$', hello),
    url(r'^time/$', current_datetime),
    url(r'^time/plus/(\d{1,2})/$', hours_ahead),
    url(r'^display_meta/$', display_meta),
    url(r'search_form/$', search_form), #url(r'^search_form/$', views.search_form),
    url(r'search/$', search), #url(r'^search/$', views.search),
    url(r'^contact/$', contact),
    url(r'^contact/thanks/$',thanks),
    #url(r'^contact/thanks/$', views.contact),
)

books/models.py
from django.db import models

class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    def __str__(self):
        return self.name

class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField(blank=True, null=True, verbose_name='郵件')
    #email = models.EmailField()

    def __str__(self):
        return u'%s %s' % (self.first_name, self.last_name)

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField()

    def __str__(self):
        return self.title

contact/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms

class ContactForm(forms.Form):
  subject = forms.CharField(max_length=20)
  email = forms.EmailField(required=False, label='You e-mail address')
  message = forms.CharField()

  def clean_message(self):
    message = self.cleaned_data['message']
    num_words = len(message.split())
    if num_words < 4:
      raise forms.ValidationError("Not enough words")
    return message

books/views.py
from django.shortcuts import render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail
from books.models import Book

# Create your views here.
def search(request):
  error = []
  if 'q' in request.GET:
    q = request.GET['q']
    if not q:
      error.append('Enter a search term')
    elif len(q) > 20:
      error.append('Please enter at most 20 characters')
    else:
      books = Book.objects.filter(title__icontains=q)
      return render_to_response('books/search_results.html',{'books':books, 'query':q})
  return render_to_response('books/search_form.html',{'error':error})
  #if 'q' in request.GET and request.GET['q']:
  #  q = request.GET['q']
  #  books = Book.objects.filter(title__icontains=q)
  #  return render_to_response('books/search_results.html', {'books':books, 'query':q})
    #message = "You searched for : %r" % request.GET['q']
  #else:
  #  return render_to_response('books/search_form.html', {'error':True})
    #return HttpResponse('Please submit a search term')
    #message = "You submitted an empty form."
  #return HttpResponse(message)

def search_form(request):
  return render_to_response('books/search_form.html',)

contact/views.py
from django.shortcuts import render_to_response, RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail
from contact.forms import ContactForm

# Create your views here.
def contact(request):
  if request.method == 'POST':
    form = ContactForm(request.POST)
    if form.is_valid():
      cd = form.cleaned_data
      return render_to_response('contact/thanks.html',{'subject':cd['subject']})
      #send_mail(cd['subject'],cd['message'],cd.get('email','noreply@exam.com'),['site@exam.com'],)
      #return HttpResponseRedirect('thanks/',{'subject':cd['subject']})
  else:
    form = ContactForm(initial={'subject':'Test site'})
  return render_to_response('contact/contact_form.html',{'form':form}, context_instance=RequestContext(request))
  #errors = []
  #if request.method == 'POST':
  #  subject = request.POST['subject']
  #  message = request.POST['message']
  #  email = request.POST.get('email','noreply@example.com')
  #  if not request.POST.get('subject',''):
  #    errors.append('Enter a subject')
  #  if not request.POST.get('message',''):
  #    errors.append('Enter a message')
  #  if request.POST.get('email') and '@' not in request.POST['email']:
  #    errors.append('Enter a valid e-mail address')
  #if not errors:
  #  errors.append('no errors')
    ##return HttpResponseRedirect('/contact/thanks/')
    ##send_mail(subject, message, email ,['weiren0516@gmail.com'],)
  #return render_to_response('contact/contact_form.html', {'errors':errors,'subject': request.POST.get('subject', ''),'message': request.POST.get('message', ''),'email': request.POST.get('email', '')}, context_instance=RequestContext(request))

def thanks(request):
  return render_to_response('contact/thanks.html')

website/views.py
#from django.template.loader import get_template
#from django.template import Context
from django.shortcuts import render_to_response
from django.http import HttpResponse
import datetime

def hello(request):
  return HttpResponse("Hello World!")

def current_datetime(request):
  current_date = datetime.datetime.now()
  return render_to_response('test/current_datetime.html', locals())

  #now = datetime.datetime.now()
  #return render_to_response('current_datetime.html',{'current_date':now})
  
  #t = get_template('current_datetime.html')
  #html = t.render(Context({'current_date':now}))
  #return HttpResponse(html)

#def current_datetime(request):
#  now = datetime.datetime.now()
#  html = "<html><body>It is now %s.</body></html>" % now
#  return HttpResponse(html)

#def hours_ahead(request, hour_offset):
  #try:
  #  hour_offset = int(hour_offset)
  #except ValueError:
  #  raise Http404()
  #next_time = datetime.datetime.now() + datetime.timedelta(hours=hour_offset)
  #return render_to_response('test/hours)ahead.html',{'hour_offset':hour_offset,'next_time':next_time})
  #return render_to_response('test/hours_ahead.html', locals())
  #html = "<html><body>In %s hour(s), it will be %s.</body></html>" % (offset, dt)
  #return HttpResponse(html)
def hours_ahead(request, hour_offset):
  try:
    hour_offset = int(hour_offset)
  except ValueError:
    raise Http404()
  next_time = datetime.datetime.now() + datetime.timedelta(hours=hour_offset)
  return render_to_response('test/hours_ahead.html', locals())
  #return render_to_response('test/hours_ahead.html', ({'hour_offset':hour_offset,'next_time':next_time}))
  #return render_to_response('test/hours_ahead.html', ({'hour_offset':hour_offset,'next_time':next_time}))

def display_meta(request):
  values = request.META.items()
  values = sorted(values)
  return render_to_response('test/display_meta.html', locals())  

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <h1>My helpful timestamp site</h1>
    {% block content %}{% endblock %}
    {% block footer %}
    <hr>
    <p>Thanks for visiting my site.</p>
    {% endblock %}
</body>
</html>

templates/books/search_form.html
<html>
<head>
    <title>Search</title>
</head>
<body>
    {% if error %}
      {% for err in error %}
        <p style="color: red;">{{err}}</p>
      {% endfor %}
    {% endif %}
    <form action="" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
</html>

templates/books/search_results.html
<p> You searched for : <strong>{{ query }}</strong></p>
{% if books %}
  <p>Found {{ books|length }} book{{ books|pluralize }}</p>
  <ul>
    {% for book in books %}
      <li>{{ book.title }}</li>
    {% endfor %}
  </ul>
{% else %}
  <p>No books matched you search criteria.</p>
{% endif %}

templates/contact/contact_form.html
<html>
<head>
    <title>Contact us</title>
</head>
<style type="text/css">
    ul.errorlist {
        margin: 0;
        padding: 0;
    }
    .errorlist li {
        background-color: red;
        color: white;
        display: block;
        font-size: 10px;
        margin: 0 0 3px;
        padding: 4px 5px;
    }
</style>
<body>
    <h1>Contact us</h1>

    {% if form.errors %}
         <p style="color:red;">Please correct the error{{ form.errors|pluralize }} below.</p>
    {% endif %}

    <form action="" method="post">
    {% csrf_token %}
      <!-- <table>
        {{ form.as_table }}
      </table> -->
        <div class="field">
            {{ form.subject.errors }}
            <label for="id_subject">Subject:</label>
            {{ form.subject }}
        </div>
        <div class="field">
            {{ form.email.errors }}
            <label for="id_email">Your e-mail address:</label>
            {{ form.email }}
        </div>
        <div class="field">
            {{ form.message.errors }}
            <label for="id_message">Message:</label>
            {{ form.message }}
        </div>
      <input type="submit" value="Submit">
    </form>
    <!-- <form action="/contact/" method="post">
        {% csrf_token %}
        <p>Subject: <input type="text" name="subject" value="{{subject}}"></p>
        <p>Your e-mail (optional): <input type="text" name="email" value="{{email}}"></p>
        <p>Message: <textarea name="message" rows="10" cols="50" value="{{message}}"></textarea></p>
        <input type="submit" value="Submit">
    </form> -->
</body>
</html>

templates/contact/thanks.html
SendMail Success
</br>
{{ subject }}

website/templates/current_datetime.html
<html><body>It is now {{current_date}}</body></html>